/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './user.module';
class UserModuleInjector extends import0.ɵNgModuleInjector<import1.UserModule> {
  _UserModule_0:import1.UserModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.UserModule {
    this._UserModule_0 = new import1.UserModule();
    return this._UserModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.UserModule)) { return this._UserModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const UserModuleNgFactory:import0.NgModuleFactory<import1.UserModule> = new import0.NgModuleFactory<any>(UserModuleInjector,import1.UserModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RhdmUvRGV2ZWxvcG1lbnQvR3l1bnUvbmctdXNlci9zcmMvdXNlci5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZGF2ZS9EZXZlbG9wbWVudC9HeXVudS9uZy11c2VyL3NyYy91c2VyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
